name: Reviewer to Assignee

on:
  pull_request:
    types: [review_requested, review_request_removed]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload.pull_request)
            const reviewers = context.payload.pull_request.requested_reviewers.map(a => a.login);
            const assignees = context.payload.pull_request.assignees.map(a => a.login);
            const assigneesToAdd = reviewers.filter(a => !assignees.includes(a));
            const assigneesToRemove = assignees.filter(a => !reviewers.includes(a));
            
            if (assigneesToRemove.length > 0) {
              github.issues.removeAssignees({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: assigneesToRemove
              });
            }
            
            if (assigneesToAdd.length > 0) {
              github.issues.addAssignees({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: assigneesToAdd
              });
            }
