name: Reviewer to Assignee

on:
  pull_request:
    types: [review_requested, review_request_removed]

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const reviewers = github.pulls.listRequestedReviewers({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(context.payload.pull_request)
            const users = reviewers.users.map(a => a.login);
            github.issues.addAssignees({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: users
            });
            
